//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCartWF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clients
    {
        public Clients()
        {
            this.Inspections = new HashSet<Inspections>();
            this.RentAndReturns = new HashSet<RentAndReturns>();
        }
    
        public int ID { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string IDCard { get; set; }
        [Required]
        public string CreditCard { get; set; }
        public Nullable<float> CreditLimit { get; set; }
        public string PersonType { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<Inspections> Inspections { get; set; }
        public virtual ICollection<RentAndReturns> RentAndReturns { get; set; }
    }
}
