//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCartWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Inspections = new HashSet<Inspections>();
            this.RentAndReturns = new HashSet<RentAndReturns>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string IDCard { get; set; }
        public string WorkShift { get; set; }
        public Nullable<float> CommissionPercentage { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string State { get; set; }
        public string Password { get; set; }
        public string Rol { get; set; }

        public virtual ICollection<Inspections> Inspections { get; set; }
        public virtual ICollection<RentAndReturns> RentAndReturns { get; set; }
    }
}
