//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCartWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspections
    {
        public int ID { get; set; }
        public int VehicleID { get; set; }
        public int ClientID { get; set; }
        public string HaveScratches { get; set; }
        public string FuelAmount { get; set; }
        public string HasSpareTire { get; set; }
        public string HasJack { get; set; }
        public string HaveBrokenGlass { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int EmployeeID { get; set; }
        public string TiresSate { get; set; }
        public string State { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
