//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCartWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModels
    {
        public VehicleModels()
        {
            this.Vehicles = new HashSet<Vehicles>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual ICollection<Vehicles> Vehicles { get; set; }
    }
}
