//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCartWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles
    {
        public Vehicles()
        {
            this.Inspections = new HashSet<Inspections>();
            this.RentAndReturns = new HashSet<RentAndReturns>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ChassisNumber { get; set; }
        public Nullable<int> EngineNumber { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public string State { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual ICollection<Inspections> Inspections { get; set; }
        public virtual ICollection<RentAndReturns> RentAndReturns { get; set; }
        public virtual VehicleModels VehicleModels { get; set; }
        public virtual VehicleTypes VehicleTypes { get; set; }
    }
}
